TrajectoryPlannerROS:
    # Robot Configuration Parameters
    max_vel_x: 0.03
    min_vel_x: -0.03
    max_vel_theta:  0.3
    min_vel_theta: -0.3
    min_in_place_vel_theta: 0.3
    escape_vel: -0.03

    acc_lim_x: 6.0
    acc_lim_y: 6.0
    acc_lim_theta: 6.0

    holonomic_robot: true
    y_vels: [-0.03, -0.01, 0.01, 0.03]

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.05
    yaw_goal_tolerance: 0.17

    # Forward Simulation Parameters
    sim_time: 7 # The amount of time to forward-simulate trajectories in seconds

    publish_cost_grid: true

    # Trajectory Scoring Parameters
    meter_scoring: true
    path_distance_bias: 2.50
    goal_distance_bias: 0.01
    occdist_scale: 4.0
