global_costmap:
    global_frame: odom
    robot_base_frame: ground
    update_frequency: 2.0
    static_map: true # Initialize with a map?

    # How far away an obstacle is from the path before it begins incurring a cost
    inflation_radius: 0.28
