local_costmap:
    global_frame: odom
    robot_base_frame: ground
    update_frequency: 2.0
    publish_frequency: 2.0
    transform_tolerance: 2.0
    static_map: false
    rolling_window: true # centers costmap around the robot as it moves
    # always_send_full_costmap: true
    width: 1.5
    height: 1.5
    # resolution: 0.025
    resolution: 0.05

    # How far away an obstacle is from the path before it begins incurring a cost
    inflation_radius: 0.03

    # http://wiki.ros.org/range_sensor_layer
